meson: add missing -lm depend for atomix binary
Without the change linkage fails on clang-13 as:

    ld: src/libatomix.a.p/canvas_helper.c.o: undefined reference to symbol 'ceil@@GLIBC_2.2.5'
    ld: ...-glibc-2.34-115/lib/libm.so.6: error adding symbols: DSO missing from command line